image: maven:3.5-jdk-8

stages:
  - build

before_script:
  - apt-get update
  - apt-get install -y openjfx
  - wget https://repo.semoss.org/semoss/Semoss/-/jobs/artifacts/svn/dev/raw/target/semoss-0.0.1-SNAPSHOT.jar?job=build -O semoss.jar
  - ls -l
  - mvn install:install-file -Dfile=semoss.jar -DgroupId=org.semoss -DartifactId=semoss -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar
  
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - .m2/repository/
  key: ${CI_BUILD_REF_NAME}
  
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/
