<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.semoss</groupId>
	<artifactId>monolith</artifactId>
	<version>${ci.version}</version>
	<packaging>war</packaging>
	<name>Monolith</name>
	<description>SEMOSS Monolith</description>
	<url>http://semoss.org/</url>
	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
		<license>
			<name>The GNU General Public License, Version 3.0</name>
			<url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>Group Mailbox</name>
			<email>semoss@semoss.org</email>
			<organization>SEMOSS</organization>
			<organizationUrl>http://semoss.org/</organizationUrl>
		</developer>
	</developers>
	<scm>
		<connection>scm:git:git://repo.semoss.org/semoss/Monolith.git</connection>
		<developerConnection>scm:git:ssh://repo.semoss.org:semoss/Monolith.git</developerConnection>
		<url>https://repo.semoss.org/semoss/Monolith</url>
	</scm>
	<properties>
		<ci.version>0.0.1-SNAPSHOT</ci.version>
		<project.build.sourceEncoding>cp1252</project.build.sourceEncoding>
		<project.reporting.outputEncoding>cp1252</project.reporting.outputEncoding>
		<openhtml.version>1.0.1</openhtml.version>
	</properties>
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>
	<build>
		<sourceDirectory>src</sourceDirectory>
	</build>
	<profiles>
		<profile>
			<id>dev</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.3</version>
						<configuration>
							<source>1.8</source>
							<target>1.8</target>
							<encoding>cp1252</encoding>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.3.2</version>
						<configuration>
							<webXml>WebContent/WEB-INF/web.xml</webXml>
							<failOnMissingWebXml>true</failOnMissingWebXml>
							<attachClasses>true</attachClasses>
							<warSourceDirectory>${basedir}/WebContent</warSourceDirectory>
							<warSourceIncludes>
								accountLocked/**,
								error/**,
								logout/**,
								noUserFail/**,
								saml2/**,
								samlLogin/**,
								samlSPLogin/**,
								sessionCounterFail/**,
								setAdmin/**,
								share/**,
								startUpFail/**,
							</warSourceIncludes>
						</configuration>
					</plugin>
					<plugin>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>2.10</version>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>deploy</id>
			<!-- note that this only works for jdk [1.8,) -->
			<!-- however, the following would enable this profile, -->
			<!-- and we want to stick with dev unless -P deploy is given
			explicitly -->
			<!--activation>
				<jdk>[1.8,)</jdk>
			</activation-->
			<!-- disabling javadoc lint - ideally should clean up javadocs -->
			<!-- see https://stackoverflow.com/a/16743137/9612364 -->
			<properties>
				<javadoc.opts>-Xdoclint:none</javadoc.opts>
			</properties>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.3</version>
						<configuration>
							<source>1.8</source>
							<target>1.8</target>
							<encoding>cp1252</encoding>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.3.2</version>
						<configuration>
							<webXml>WebContent/WEB-INF/web.xml</webXml>
							<failOnMissingWebXml>true</failOnMissingWebXml>
							<attachClasses>true</attachClasses>
							<warSourceDirectory>${basedir}/WebContent</warSourceDirectory>
							<warSourceIncludes>
								accountLocked/**,
								error/**,
								logout/**,
								noUserFail/**,
								saml2/**,
								samlLogin/**,
								samlSPLogin/**,
								sessionCounterFail/**,
								setAdmin/**,
								share/**,
								startUpFail/**,
							</warSourceIncludes>
							<packagingExcludes>
								%regex[WEB-INF/lib/(?!semoss-${ci.version}).*.jar]
							</packagingExcludes>
						</configuration>
					</plugin>
					<plugin>
						<artifactId>maven-assembly-plugin</artifactId>
						<version>2.5.3</version>
						<configuration>
							<descriptor>libraries.xml</descriptor>
						</configuration>
						<executions>
							<execution>
								<id>create-archive</id>
								<phase>package</phase>
								<goals>
									<goal>single</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.sonatype.plugins</groupId>
						<artifactId>nexus-staging-maven-plugin</artifactId>
						<version>1.6.7</version>
						<extensions>true</extensions>
						<configuration>
							<serverId>ossrh</serverId>
							<nexusUrl>https://oss.sonatype.org/</nexusUrl>
							<!-- set to true to disable manual review of release -->
							<autoReleaseAfterClose>false</autoReleaseAfterClose>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.5</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
								<configuration>
									<gpgArguments>
										<arg>--pinentry-mode</arg>
										<arg>loopback</arg>
									</gpgArguments>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<executions>
							<execution>
								<id>attach-sources</id>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>2.9.1</version>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
								<!-- disabling javadoc lint - ideally should
								clean up javadocs -->
								<configuration>
									<additionalparam>${javadoc.opts}</additionalparam>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<repositories>
		<repository>
			<id>public</id>
			<name>Sonatype's Maven repository</name>
			<url>https://oss.sonatype.org/content/groups/public</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>central</id>
			<name>Maven Repository Switchboard</name>
			<layout>default</layout>
			<url>https://repo1.maven.org/maven2</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>snapshot</id>
			<name>Sonatype's Maven repository - SNAPSHOT</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>3rdPartyJARs</id>
			<name>Maven repository</name>
			<url>https://maven.semoss.org/repository/3rdPartyJARs</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<!-- repository for Apache Storm -->
		<!-- <repository> <id>clojars.org</id>
		<url>http://clojars.org/repo</url> 
		</repository> -->
		<repository>
			<id>redshift</id>
			<url>https://s3.amazonaws.com/redshift-maven-repository/release</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>org.semoss</groupId>
			<artifactId>semoss</artifactId>
			<version>${ci.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.websocket/javax.websocket-api -->
		<dependency>
			<groupId>javax.websocket</groupId>
			<artifactId>javax.websocket-api</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-core -->
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-core</artifactId>
			<version>4.7.9.Final</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-jaxb-provider -->
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jaxb-provider</artifactId>
			<version>4.7.9.Final</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-multipart-provider -->
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-multipart-provider</artifactId>
			<version>4.7.9.Final</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- This is actually needed for reasteasy - do not remove it -->
		<!-- https://mvnrepository.com/artifact/com.sun.mail/javax.mail -->
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>1.6.2</version>
		</dependency>
		<!-- SAML ONE JAR -->
		<!-- https://mvnrepository.com/artifact/org.openidentityplatform.openam/openam-federation-library -->
		<dependency>
			<groupId>org.openidentityplatform.openam</groupId>
			<artifactId>openam-federation-library</artifactId>
			<version>14.8.4</version>
			<exclusions>
				<exclusion>
					<groupId>javax.mail</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.mail</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.owasp.esapi</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.woodstox</groupId>
					<artifactId>woodstox-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjdk.nashorn</groupId>
					<artifactId>nashorn-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- adding updated jar to deal with exclusion w/ vulnerability -->
		<!-- https://mvnrepository.com/artifact/com.fasterxml.woodstox/woodstox-core -->
		<dependency>
			<groupId>com.fasterxml.woodstox</groupId>
			<artifactId>woodstox-core</artifactId>
			<version>5.4.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.activation/activation -->
		<!-- required for openam compilation without com.sum.mail -->
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on -->
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk18on</artifactId>
			<version>1.78.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.mikesamuel/json-sanitizer -->
		<dependency>
		    <groupId>com.mikesamuel</groupId>
		    <artifactId>json-sanitizer</artifactId>
		    <version>1.2.3</version>
		</dependency>
	</dependencies>
</project>
