package prerna.semoss.web.services;

import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

import prerna.poi.main.insights.AutoInsightExecutor;
import prerna.rdf.engine.api.IEngine;
import prerna.rdf.engine.impl.AbstractEngine;
import prerna.web.services.util.WebUtility;

public class AutoGeneratedInsights {

	private IEngine engine;
	
	public AutoGeneratedInsights(IEngine engine) {
		this.engine = engine;
	}
	
	@POST
	@Path("/runGenerateInsights")
	public Response runGenerateInsights() {
		AutoInsightExecutor executor = new AutoInsightExecutor((AbstractEngine) engine);
		boolean success = executor.run();
		
		return Response.status(200).entity(WebUtility.getSO(success)).build();
	}

}
