//package prerna.semoss.web.services;
//
//import javax.ws.rs.POST;
//import javax.ws.rs.Path;
//import javax.ws.rs.core.Response;
//
//import prerna.engine.api.IEngine;
//import prerna.engine.impl.AbstractEngine;
//import prerna.poi.main.insights.AutoInsightExecutor;
//import prerna.web.services.util.WebUtility;
//
//public class AutoGeneratedInsights {
//
//	private IEngine engine;
//	
//	public AutoGeneratedInsights(IEngine engine) {
//		this.engine = engine;
//	}
//	
//	@POST
//	@Path("/runGenerateInsights")
//	public Response runGenerateInsights() {
//		AutoInsightExecutor executor = new AutoInsightExecutor((AbstractEngine) engine);
//		executor.run();
//		if(executor.isSuccess()) {
////			return Response.status(200).entity(WebUtility.getSO("Successfully generated insights")).build();
//			return WebUtility.getResponse("Successfully generated insights", 200);
//		} else {
////			return Response.status(400).entity(WebUtility.getSO("Failed to generate insights")).build();
//			return WebUtility.getResponse("Failed to generate insights", 200);
//		}
//	}
//
//}
