/*******************************************************************************
 * Copyright 2015 Defense Health Agency (DHA)
 *
 * If your use of this software does not include any GPLv2 components:
 * 	Licensed under the Apache License, Version 2.0 (the "License");
 * 	you may not use this file except in compliance with the License.
 * 	You may obtain a copy of the License at
 *
 * 	  http://www.apache.org/licenses/LICENSE-2.0
 *
 * 	Unless required by applicable law or agreed to in writing, software
 * 	distributed under the License is distributed on an "AS IS" BASIS,
 * 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * 	See the License for the specific language governing permissions and
 * 	limitations under the License.
 * ----------------------------------------------------------------------------
 * If your use of this software includes any GPLv2 components:
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *******************************************************************************/
package prerna.semoss.web.services.local;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import javax.annotation.security.PermitAll;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import prerna.auth.AccessToken;
import prerna.auth.AuthProvider;
import prerna.auth.User;
import prerna.om.ThreadStore;
import prerna.reactor.automation.AutomationConstants;
import prerna.util.AssetUtility;
import prerna.util.Constants;
import prerna.web.requests.OverrideParametersServletRequest;

/**
 * REST endpoint that allows external systems to trigger an automation via webhook.
 *
 * <p>POST /api/automation/{projectId}/trigger
 *   Header: X-Webhook-Secret: &lt;secret&gt;
 *
 * <p>The secret is stored in the project's {@code automation-config.json} under the key
 * {@code WEBHOOK_SECRET}. It is generated by the {@code GenerateAutomationWebhookSecret}
 * pixel reactor, which also records the requesting user under {@code WEBHOOK_USER} so
 * the execution runs with the correct identity. The caller must present the same secret
 * in the {@code X-Webhook-Secret} request header; requests with a missing or invalid
 * secret are rejected with 401.
 *
 * <p>On success, {@code TriggerAutomation(project=["projectId"], triggerType=["WEBHOOK"])}
 * is executed in scheduler mode and the run-summary JSON is returned.
 *
 * <p>This endpoint bypasses the normal session-presence check — see
 * {@code NoUserInSessionFilter#isAutomationWebhookPath}.
 */
@Path("/automation")
@PermitAll
public class AutomationWebhookResource {

	private static final Logger classLogger = LogManager.getLogger(AutomationWebhookResource.class);
	private static final Gson GSON = new GsonBuilder().disableHtmlEscaping().create();

	private static final String WEBHOOK_SECRET_KEY = "WEBHOOK_SECRET";
	private static final String WEBHOOK_USER_KEY   = "WEBHOOK_USER";
	private static final String SECRET_HEADER      = "X-Webhook-Secret";

	@POST
	@Path("/{projectId}/trigger")
	@Consumes(MediaType.WILDCARD)
	@Produces(MediaType.APPLICATION_JSON)
	public Response trigger(
			@PathParam("projectId") String projectId,
			@Context HttpServletRequest request) {

		if (projectId == null || projectId.isBlank()) {
			return errorResponse(Response.Status.BAD_REQUEST, "projectId is required");
		}

		// --- secret validation -------------------------------------------------------

		String incomingSecret = request.getHeader(SECRET_HEADER);
		if (incomingSecret == null || incomingSecret.isBlank()) {
			classLogger.warn("Automation webhook for project {} missing {} header", projectId, SECRET_HEADER);
			return errorResponse(Response.Status.UNAUTHORIZED, "Missing " + SECRET_HEADER + " header");
		}

		String storedSecret = readConfigValue(projectId, WEBHOOK_SECRET_KEY);
		if (storedSecret == null) {
			classLogger.warn("Automation webhook for project {} but no secret is configured", projectId);
			return errorResponse(Response.Status.UNAUTHORIZED, "Webhook not configured for this automation");
		}

		// constantTimeEquals guards against timing-based secret enumeration
		if (!constantTimeEquals(incomingSecret, storedSecret)) {
			classLogger.warn("Automation webhook for project {} presented invalid secret", projectId);
			return errorResponse(Response.Status.UNAUTHORIZED, "Invalid webhook secret");
		}

		// --- user identity -----------------------------------------------------------

		String userSpec = readConfigValue(projectId, WEBHOOK_USER_KEY);
		if (userSpec == null || userSpec.isBlank()) {
			classLogger.warn("Automation webhook for project {} has no stored user — regenerate the webhook secret", projectId);
			return errorResponse(Response.Status.UNAUTHORIZED,
					"Webhook user not configured. Regenerate the webhook secret to fix this.");
		}

		HttpSession session = request.getSession(true);
		session.setAttribute(Constants.SESSION_USER, buildWebhookUser(userSpec));

		// --- pixel execution ---------------------------------------------------------

		String pixel = String.format(
				"TriggerAutomation(project=[\"%s\"], triggerType=[\"%s\"]);",
				projectId, AutomationConstants.TRIGGER_WEBHOOK);

		ThreadStore.setSchedulerMode(true);
		NameServer ns = new NameServer();
		OverrideParametersServletRequest requestWrapper = new OverrideParametersServletRequest(request);
		Map<String, String> paramMap = new HashMap<>();
		paramMap.put("expression", pixel);
		requestWrapper.setParameters(paramMap);

		try {
			classLogger.info("Automation webhook triggered for project {}", projectId);
			return ns.runPixelSync(requestWrapper);
		} catch (Exception e) {
			classLogger.error("Automation webhook execution failed for project {}: {}", projectId, e.getMessage(), e);
			return errorResponse(Response.Status.INTERNAL_SERVER_ERROR, e.getMessage());
		} finally {
			try { session.invalidate(); } catch (Exception ignored) {}
		}
	}

	/**
	 * Reconstructs a transient {@link User} from the stored provider:userId spec.
	 * Format stored by GenerateAutomationWebhookSecret: {@code PROVIDER:userId[,PROVIDER:userId]}.
	 */
	private User buildWebhookUser(String userSpec) {
		User user = new User();
		for (String pair : userSpec.split(",")) {
			String[] parts = pair.split(":", 2);
			if (parts.length != 2) {
				continue;
			}
			try {
				AuthProvider provider = AuthProvider.valueOf(parts[0]);
				AccessToken token = new AccessToken();
				token.setProvider(provider);
				token.setId(parts[1]);
				token.setName("webhook_" + UUID.randomUUID());
				user.setAccessToken(token);
			} catch (IllegalArgumentException e) {
				classLogger.warn("Unknown auth provider in automation webhook user config: {}", parts[0]);
			}
		}
		return user;
	}

	/**
	 * Reads a single value from the project's {@code automation-config.json}.
	 * The file is a JSON array where each element is {@code {key, value, sensitive}}.
	 */
	private String readConfigValue(String projectId, String key) {
		try {
			String portalsFolder = AssetUtility.getProjectPortalsFolder(projectId);
			File configFile = new File(portalsFolder + "/" + AutomationConstants.AUTOMATION_CONFIG_FILE_NAME);
			if (!configFile.exists()) {
				return null;
			}
			String json = Files.readString(configFile.toPath(), StandardCharsets.UTF_8);
			List<Map<String, Object>> entries = GSON.fromJson(json,
					new TypeToken<List<Map<String, Object>>>() {}.getType());
			if (entries == null) {
				return null;
			}
			for (Map<String, Object> entry : entries) {
				if (key.equals(entry.get("key"))) {
					Object val = entry.get("value");
					return val != null ? val.toString() : null;
				}
			}
		} catch (Exception e) {
			classLogger.warn("Could not read automation config for project {}: {}", projectId, e.getMessage());
		}
		return null;
	}

	/** Timing-safe byte comparison via stdlib — prevents timing-based secret enumeration. */
	private static boolean constantTimeEquals(String a, String b) {
		return MessageDigest.isEqual(
				a.getBytes(StandardCharsets.UTF_8),
				b.getBytes(StandardCharsets.UTF_8));
	}

	private static Response errorResponse(Response.Status status, String message) {
		return Response.status(status)
				.type(MediaType.APPLICATION_JSON)
				.entity("{\"error\":\"" + message + "\"}")
				.build();
	}
}
